name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup GitHub Action for Deno
      uses: denolib/setup-deno@v1.1.0
    - run: deno test -A
